name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install deps
        run: |
          cd frontend
          npm ci
      - name: Run Tests
        run: |
          cd frontend
          npm run test:ci
      - name: Build
        run: |
          cd frontend
          npm run build
      - name: Deploy
        if: success()
        run: ./deploy.sh deploy-all
